### ISSUE TITLE
account_id input in log group arn can be removed

### ISSUE THREAD

**Issue by nitrocode** [nabeken/terraform-aws-ecs-drain-lambda#5]
https://github.com/nabeken/terraform-aws-ecs-drain-lambda/blob/6b8ed28d3f1672dfcfd9ca440ea5ef7c5c1a295e/main.tf#L46

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

```hcl
  # ...

  "${aws_cloudwatch_log_group.main.arn}:*",

  # ...
```

**Comment by nabeken** [comment]
@nitrocode Thank you for the suggestion!
